### ISSUE TITLE
Document AWS lambda and AWS gateway usage for cord-19 app

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/cord-19#106]
Some best practises would help if one wants different authentication than what Vespa cloud offers (mTLS).

**Comment by jobergum** [comment]
@freva @oyving  FYI

**Comment by kkraune** [comment]
there is some doc at https://github.com/vespa-engine/sample-apps/tree/master/vespa-cloud/vespa-documentation-search - is it something like this / more of it you want?

**Comment by jobergum** [comment]
Yes, exactly like that @kkraune :)

**Comment by kkraune** [comment]
ok - I will add a section on this, linking to https://github.com/vespa-engine/sample-apps/tree/master/vespa-cloud/vespa-documentation-search for details then

**Comment by kkraune** [comment]
https://github.com/vespa-engine/cord-19/pull/108 links to doc - close if this is satisfactory
