### ISSUE TITLE
Link to Backed page not found

### ISSUE THREAD

**Issue by yashodhara314e** [vespa-engine/cord-19#131]
In the readme file of the repository, there are link to backend code of the page.
https://github.com/vespa-engine/sample-apps/tree/master/vespa-cloud/cord-19-search
But, link is giving 404 page not found error. Kindly update and provide link to backed code of CORD-19.

**Comment by kkraune** [comment]
Thanks for reporting! fixed in https://github.com/vespa-engine/cord-19/pull/132
