### ISSUE TITLE
filter by journal doesn't appear to work as expected 

### ISSUE THREAD

**Issue by tracy55** [vespa-engine/cord-19#89]
I would like to filter results by journal but the API does not seem to be respecting the filter and returns random journals while the FE search works as expected:

api: https://api.cord19.vespa.ai/search/?query=covid-19&summary=short&ranking=freshness&year=2020&fieldset=all&journal=The+Lancet
FE:  https://cord19.vespa.ai/search?query=covid-19&summary=short&ranking=freshness&year=2020&fieldset=all&journal=The+Lancet

Am I doing something wrong?

**Comment by frodelu** [comment]
@tracy55 Thank you for filing this.

When querying the API, you cannot use the same GET parameters as you see in the frontend or the frontend query language. You need to use the [Vespa YQL query language](https://docs.vespa.ai/documentation/query-language.html) through the [Vespa Search API](https://docs.vespa.ai/documentation/search-api.html).

Some examples are listed in the [CORD-19 documentation](https://github.com/vespa-engine/cord-19/blob/master/cord-19-queries.md) under ["Example API queries"](https://github.com/vespa-engine/cord-19/blob/master/cord-19-queries.md#example-api-queries). 

I'll update this issue with your exact query shortly.

**Comment by frodelu** [comment]
@tracy55 Your specific FE query would translate to something like this:
https://api.cord19.vespa.ai/search/?query=covid-19&summary=short&ranking=freshness&yql=select%20*%20from%20sources%20*%20where%20userQuery()%20and%20timestamp%20%3E%201577836800%20and%20journal%20contains%20%22the%20lancet%22%3b

Or - if using a POST request with the JSON (a bit easier to work with) it would look like this:
```
{
  'yql': 'select * from sources * where userQuery() and timestamp > 1577836800 and journal contains "the lancet";',
  'summary': 'short',
  'query': 'covid-19',
  'ranking': 'freshness'
}
```

Hope this helps.

**Comment by tracy55** [comment]
Thank you @frodelu this is very helpful, much appreciated.

**Comment by tracy55** [comment]
@frodelu I'm noticing some latency, what is the expected sla for this sample call https://api.cord19.vespa.ai/search/?query=covid-19&summary=short&hits=20&ranking=freshness&yql=select+*+from+sources+*+where+userQuery%28%29+and+timestamp+%3E+1577836800%3B

**Comment by bratseth** [comment]
About 10-15 ms. Where are you calling us from, and do you use persistent connections?
